### ISSUE TITLE
Please post chat binary code

### ISSUE THREAD

**Issue by webbrandon** [ohmplatform/FreedomGPT#11]
The community wants to support this project but there is a lot of doubt.  Can we please post or reference the code for the binary that is used to spawn model?

**Comment by webbrandon** [comment]
I guess I may have to test myself but hoping this is the chat binary foundation you provided: https://github.com/ggerganov/llama.cpp

**Comment by ItsPi3141** [comment]
it's alpaca.cpp
https://github.com/ohmplatform/FreedomGPT/commit/e28a8a8651d33cd901d97f3ec718b22940beba70
