### ISSUE TITLE
[Question] Download link for Windows App?

### ISSUE THREAD

**Issue by gaveitatry2** [ohmplatform/FreedomGPT#116]
There is a five month old thread here on the FreedomGPT GitHub that has a Windows App download link, but it's for an old version.

I went to the FreedomGPT website and when I try to download the Windows App from there it tells me "We will email you when the Windows version is available".

Why is it so hard to freaking get the Windows App for FreedomGPT downloaded on my computer?

**Comment by mhtvsSFrpHdE** [comment]
Hi

I noticed that Windows setup.exe is already available for download in 2.0.1 Release page.
