### ISSUE TITLE
Windows 2.0.1 both liberty and scarlett not run

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [ohmplatform/FreedomGPT#120]
![image](https://github.com/ohmplatform/FreedomGPT/assets/10773245/f70cc44f-931e-4584-a9d0-88e988b89241)
Stops at "Stop Generating"

**Comment by RafaelLorenzoni** [comment]
Same here, but I was trying to run in a Acer laptop with a Ryzen 5 3500U processor with 8GB RAM.

**Comment by mhtvsSFrpHdE** [comment]
First I notice that `AppData\Local\FreedomGPT\app-2.0.1\resources\models` is a blank folder  
with only file `_._`, instead of folder `llama` and `main.exe` which is exist in version `1.1.3`.

After paste the folder from `1.1.3`, I was able to get old version models to work,  
by using "BRING YOUR OWN MODEL", "ggml-model-q4_0.bin":
![image](https://github.com/ohmplatform/FreedomGPT/assets/10773245/763a5cca-1b27-409b-ac89-8d626e3e8ffb)

However, new models still not work, I tried call `main.exe` directly and get these:
```
main.exe -m "<path to new model>\scarlett-7b.ggmlv3.q5_1.bin"
main: build = 1112 (d4b5e16)
main: seed  = 1693308719
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from <path to new model>\scarlett-7b.ggmlv3.q5_1.bin

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '<path to new model>\scarlett-7b.ggmlv3.q5_1.bin'
main: error: unable to load model
```

**Comment by mhtvsSFrpHdE** [comment]
If I use old version `main.exe` and call `main.exe -m "<path to old model>\ggml-model-q4_0.bin"`
```
main: seed = 1693309327
llama.cpp: loading model from <path to old model>\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  59.11 KB
llama_model_load_internal: mem required  = 5809.32 MB (+ 1026.00 MB per state)
llama_init_from_file: kv self size  =  256.00 MB
...
```

**Comment by mhtvsSFrpHdE** [comment]
I try to download llama from https://github.com/ggerganov/llama.cpp/releases/tag/b1112  
and my new `main.exe` will not recognize both new and old models.

Call b1112 `main.exe -m "<path to old model>\ggml-model-q4_0.bin"`,  
says:
```
main: build = 1112 (d4b5e16)
main: seed  = 1693309306
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from <path to old model>\ggml-model-q4_0.bin

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '<path to old model>\ggml-model-q4_0.bin'
main: error: unable to load model
```

**Comment by mhtvsSFrpHdE** [comment]
Some interesting information

https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/discussions/14

> gguf_init_from_file: invalid magic number 67676a74

> [zenitica](https://huggingface.co/zenitica)
>[6 days ago](https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/discussions/14#64e57e01aab459f4345a67ad)
>
>rolling back llama.cpp to commit hash a113689 works

> [TheBloke](https://huggingface.co/TheBloke)
> [6 days ago](https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/discussions/14#64e5bc015af55fb4d1f9b61d)
>
>Yeah, latest llama.cpp is no longer compatible with GGML models. The new model format, GGUF, was merged recently. As far as llama.cpp is concerned, GGML is now dead - though of course many third-party clients/libraries are likely to continue to support it for a lot longer. I need to update my GGML READMEs to mention this and will be doing this shortly.
>
>I will be providing GGUF models for all my repos in the next 2-3 days. I'm waiting for another PR to merge, which will add improved k-quant quantisation formats.
>
>For now, if you want to use llama.cpp you will need to downgrade it back to commit dadbed99e65252d79f81101a392d0d6497b86caa or earlier. Or use one of the llama.cpp binary releases from before GGUF was merged. Or use a third party client like KoboldCpp, LM Studio, text-generation-webui, etc.
>
>Look out for new -GGUF repos from me in the coming days. Or yes, you can convert them yourself using the script ggml_to_gguf.py now provided with llama.cpp.

**Comment by mhtvsSFrpHdE** [comment]
The a113689 can be located at here https://github.com/ggerganov/llama.cpp/releases/tag/master-a113689

I use "llama-master-a113689-bin-win-avx2-x64.zip", and it seems this version will not recognize `1.1.3` models but able to recognize `2.0.1` `scarlett-7b.ggmlv3.q5_1.bin`

Call to `main.exe -m "<path to new model>\scarlett-7b.ggmlv3.q5_1.bin"` gets:
```
main: build = 929 (a113689)
main: seed  = 1693310095
llama.cpp: loading model from <path to new model>\scarlett-7b.ggmlv3.q5_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 5504
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 4829.39 MB (+  256.00 MB per state)
llama_new_context_with_model: kv self size  =  256.00 MB
llama_new_context_with_model: compute buffer total size =   71.84 MB
...
```

Unzip the main.exe and all other zip content to `AppData\Local\FreedomGPT\app-2.0.1\resources\models\llama\main.exe`  
I was able to get scarlett run
![image](https://github.com/ohmplatform/FreedomGPT/assets/10773245/7b4131a5-f537-46ce-baf6-3bd3f4b02dbb)

@RafaelLorenzoni Try this

**Comment by mhtvsSFrpHdE** [comment]
After apply the fix, new models do start to talk, but output is random trash.

**Comment by RafaelLorenzoni** [comment]
This project is awesome. Is like "GOD POWER". Hope they fix this, so it can really work!

**Comment by mhtvsSFrpHdE** [comment]
https://github.com/ohmplatform/FreedomGPT/releases/tag/v2.5.1

2.5.1 has released.
