### ISSUE TITLE
(node:103168) electron: Failed to load URL: http://localhost:3001/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by geezluise** [ohmplatform/FreedomGPT#135]
I have everything installed but get this error which I believe is stopping the program from loading.  

Server listening on port 8888
(node:8394) electron: Failed to load URL: http://localhost:3001/ with error: ERR_CONNECTION_REFUSED
(Use electron --trace-warnings ... to show where the warning was created)
update-electron-app config looks good; aborting updates since app is in development mode
[8426:0423/042236.005243:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!

all my checks when loading on Ubuntu Linux pass and then I get the error. The gui loads up but is just blank. I can access developer tools in the GUI. All my dependencies are loaded without errors.

I am on ubuntu v22.04.4 LTS ARM64
running on an OrangePi 5B

**Comment by holdenchristiansen** [comment]
This issue should be fixed as of the latest commit. Thanks for reporting it!
