### ISSUE TITLE
Cannot execute program

### ISSUE THREAD

**Issue by ichirugame** [ohmplatform/FreedomGPT#2]
>     forge.config.ts:5:32 - error TS2307: Cannot find module './devconst' or i…
>    5 import { DEVELOPER_DATA } from "./devconst";
>                                     ~~~~~~~~~~~~
>◼ Preparing native dependencies
>◼ Running generateAssets hook
>
>An unhandled rejection has occurred inside Forge:
>TSError: ⨯ Unable to compile TypeScript:
>forge.config.ts:5:32 - error TS2307: Cannot find module './devconst' or its corresponding type declarations.
>
>5 import { DEVELOPER_DATA } from "./devconst";
>                                 ~~~~~~~~~~~~
>at createTSError (/local/node/freedom-gpt/node_modules/ts-node/src/index.ts:859:12)
>    at reportTSError (/local/node/freedom-gpt/node_modules/ts-node/src/index.ts:863:19)
>    at getOutput (/local/node/freedom-gpt/node_modules/ts-node/src/index.ts:1077:36)
>    at Object.compile (/local/node/freedom-gpt/node_modules/ts-node/src/index.ts:1433:41)
>    at Module.m._compile (/local/node/freedom-gpt/node_modules/ts-node/src/index.ts:1617:30)
>    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
>    at Object.require.extensions.<computed> [as .ts] (/local/node/freedom-gpt/node_modules/ts-node/src/index.ts:1621:12)
>    at Module.load (node:internal/modules/cjs/loader:1037:32)
>    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
>    at Module.require (node:internal/modules/cjs/loader:1061:19)
>    at require (node:internal/modules/cjs/helpers:103:18)
>    at exports.default (/local/node/freedom-gpt/node_modules/@electron-forge/core/src/util/forge-config.ts:127:22)
>    at async Task.task (/local/node/freedom-gpt/node_modules/@electron-forge/core/src/api/start.ts:63:29)
>    at async Task.run (/local/node/freedom-gpt/node_modules/listr2/dist/index.cjs:978:11)
>    at async /local/node/freedom-gpt/node_modules/p-map/index.js:57:22
>error Command failed with exit code 1.
>info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The error message is The program is not executable.
My environment is
almalinux 8
node.js version
v18.12.1
The directory is
node_modules
src
assets
build
The
What am I missing?

**Comment by ChrisKretschmer** [comment]
just remove the references in the forge.config.ts file
the app signing stuff is only needed to create and sign a macos binary

**Comment by ichirugame** [comment]
thank you.
How to start this program
yarn start
Is it okay?
yarn start
when you hit

[0401/200520.265877:FATAL:electron_main_delegate.cc(300)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Done in 16.50s.

There is a sentence.
Is it because it's a success?
Port 3000 is not used.

**Comment by ChrisKretschmer** [comment]
Well - I guess, you shouldn't run it as root

**Comment by ichirugame** [comment]
thank you.

Error launching app
Unable to find Electron app at /local/node/freedom-gpt
Cannot find module '/local/node/freedom-gpt/.webpack/main'. Please verify that the package.json has a valid "main" entry
error Command failed with exit code 1.

I get an error saying
There is no directory /local/node/freedom-gpt/.webpack/main.

**Comment by l-Aeden-l** [comment]
yarn run v1.22.19
$ APP_DEV=true electron-forge start
'APP_DEV' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by andrescarlos-gm** [comment]
> yarn run v1.22.19 $ APP_DEV=true electron-forge start 'APP_DEV' n’est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes. error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Same problem here

**Comment by Tokaroi** [comment]
yarn run v1.22.19
$ APP_DEV=true electron-forge start
'APP_DEV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ichirugame** [comment]
free-gpt doesn't seem to support Linux.
Today's update was to add support for Windows.
However, I saw an article that it works on windows, but what about it?
It's nice to support Windows and Mac, but I'd like to see Linux supported as well.

**Comment by ichirugame** [comment]
I do not know if it will be resolved.
Module not found: Error: Can't resolve 'bufferutil' in 'C:\Users\fpsbrandalm81\freedom-gpt-electron-app\node_modules\ws\lib'
Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\Users\fpsbrandalm81\freedom-gpt-electron-app\node_modules\ws\lib'
I believe this error is due to a missing module.
Installation method.
bufferutil: https://www.npmjs.com/package/bufferutil
utf-8-validate: https://www.npmjs.com/package/utf-8-validate

**Comment by jochotecoa** [comment]
C:\Users\User\freedom-gpt-electron-app>yarn start
yarn run v1.22.19
$ electron-forge start
"electron-forge" is not recognized as an internal or external command,
program or executable batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ivanbodurov** [comment]
I started it on Windows. Type it: 'Hi'. Still no response.

**Comment by ichirugame** [comment]
`yarn start:prod`
I got it working with the code above.
