### ISSUE TITLE
Stuck downloading

### ISSUE THREAD

**Issue by ChubbyFungus** [ohmplatform/FreedomGPT#28]
I've followed the instruction as far as I can tell and i get the GUI to open but it sticks at 0MB downloaded

Any ideas?

**Comment by dasein2001** [comment]
I am having the same issue. I tried: 
cd ~
rm -rf FreedomGPT
git clone https://github.com/ohmplatform/FreedomGPT.git 

and I got 

Cloning into 'FreedomGPT'...
remote: Enumerating objects: 315, done.
remote: Counting objects: 100% (315/315), done.
remote: Compressing objects: 100% (189/189), done.
remote: Total 315 (delta 178), reused 235 (delta 99), pack-reused 0
Receiving objects: 100% (315/315), 4.02 MiB | 6.40 MiB/s, done.
Resolving deltas: 100% (178/178), done.
Harolds-MacBook-Pro:~ haroldecrowe$ cd FreedomGPT
Harolds-MacBook-Pro:FreedomGPT haroldecrowe$ yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@9.1.2" has unmet peer dependency "webpack@>=5".
warning " > copy-webpack-plugin@11.0.0" has unmet peer dependency "webpack@^5.1.0".
warning " > css-loader@6.7.3" has unmet peer dependency "webpack@^5.0.0".
warning " > fork-ts-checker-webpack-plugin@7.3.0" has unmet peer dependency "webpack@^5.11.0".
warning " > node-loader@2.0.0" has unmet peer dependency "webpack@^5.0.0".
warning " > style-loader@3.3.2" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-loader@9.4.2" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[#####################################################--------------------------------------------------------------------[######################################################-------------------------------------------------------------------[4/4] 🔨  Building fresh packages...
✨  Done in 35.39s.
Machine:FreedomGPT user$ yarn start:prod
yarn run v1.22.19
$ electron-forge start
✔ Checking your system
✔ Locating application
✔ Loading configuration
✔ Preparing native dependencies [1s]
✔ Running generateAssets hook
✔ [plugin-webpack] Compiling main process code [5s]
✔ [plugin-webpack] Launching dev servers for renderer process code [5s]
  › Output Available: http://localhost:9000

Server listening on port 8889
File does not exist
(node:15800) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:15800) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir '/Users/User/FreedomGPT'
    at Object.rmdirSync (node:fs:1226:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmdirSync (node:fs:1218:14)
    at /Users/haroldecrowe/FreedomGPT/.webpack/main/index.js:34482:26
    at Generator.next (<anonymous>)
    at /Users/User/FreedomGPT/.webpack/main/index.js:34168:71
    at new Promise (<anonymous>)
    at __webpack_modules__../src/index.ts.__awaiter (/Users/User/FreedomGPT/.webpack/main/index.js:34164:12)
    at checkIfFileExists (/Users/User/FreedomGPT/.webpack/main/index.js:34477:33)
(node:15800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

I just get this loading image and nothing happens:
![Screen Shot 2023-04-12 at 7 29 01 PM](https://user-images.githubusercontent.com/130618578/231617750-962b57cc-3e98-4da9-b15a-367b44757401.jpg)

chat GPT explains: 
"It seems like there was an error when trying to start the Freedom GPT app using Electron. The error message says that there was a problem with removing a directory, which caused an unhandled promise rejection.

One thing you could try is to manually remove the FreedomGPT directory again and try running yarn install and yarn start:prod again. Sometimes, errors can occur during installation or build processes, and retrying them can help.

Also, it looks like there are some warnings related to missing peer dependencies, which could be causing issues. You might want to try installing the missing packages or updating the existing ones.

If the issue persists, you can try looking at the specific error message and see if there are any relevant solutions or workarounds available online. Additionally, you can try reaching out to the Freedom GPT support team or community for help with troubleshooting the issue."

**Comment by dasein2001** [comment]
I am having the same issue. I tried: 
cd ~
rm -rf FreedomGPT
git clone https://github.com/ohmplatform/FreedomGPT.git 

and I got 

Cloning into 'FreedomGPT'...
remote: Enumerating objects: 315, done.
remote: Counting objects: 100% (315/315), done.
remote: Compressing objects: 100% (189/189), done.
remote: Total 315 (delta 178), reused 235 (delta 99), pack-reused 0
Receiving objects: 100% (315/315), 4.02 MiB | 6.40 MiB/s, done.
Resolving deltas: 100% (178/178), done.
User-MacBook-Pro:~ User $ cd FreedomGPT
User-MacBook-Pro:FreedomGPT User $ yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@9.1.2" has unmet peer dependency "webpack@>=5".
warning " > copy-webpack-plugin@11.0.0" has unmet peer dependency "webpack@^5.1.0".
warning " > css-loader@6.7.3" has unmet peer dependency "webpack@^5.0.0".
warning " > fork-ts-checker-webpack-plugin@7.3.0" has unmet peer dependency "webpack@^5.11.0".
warning " > node-loader@2.0.0" has unmet peer dependency "webpack@^5.0.0".
warning " > style-loader@3.3.2" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-loader@9.4.2" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[#####################################################--------------------------------------------------------------------[######################################################-------------------------------------------------------------------[4/4] 🔨  Building fresh packages...
✨  Done in 35.39s.
Machine:FreedomGPT user$ yarn start:prod
yarn run v1.22.19
$ electron-forge start
✔ Checking your system
✔ Locating application
✔ Loading configuration
✔ Preparing native dependencies [1s]
✔ Running generateAssets hook
✔ [plugin-webpack] Compiling main process code [5s]
✔ [plugin-webpack] Launching dev servers for renderer process code [5s]
  › Output Available: http://localhost:9000

Server listening on port 8889
File does not exist
(node:15800) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:15800) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir '/Users/User/FreedomGPT'
    at Object.rmdirSync (node:fs:1226:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmdirSync (node:fs:1218:14)
    at /Users/User/FreedomGPT/.webpack/main/index.js:34482:26
    at Generator.next (<anonymous>)
    at /Users/User/FreedomGPT/.webpack/main/index.js:34168:71
    at new Promise (<anonymous>)
    at __webpack_modules__../src/index.ts.__awaiter (/Users/User/FreedomGPT/.webpack/main/index.js:34164:12)
    at checkIfFileExists (/Users/User/FreedomGPT/.webpack/main/index.js:34477:33)
(node:15800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

I just get this loading image and nothing happens:
![Screen Shot 2023-04-12 at 7 29 01 PM](https://user-images.githubusercontent.com/130618578/231617750-962b57cc-3e98-4da9-b15a-367b44757401.jpg)

chat GPT explains: 
"It seems like there was an error when trying to start the Freedom GPT app using Electron. The error message says that there was a problem with removing a directory, which caused an unhandled promise rejection.

One thing you could try is to manually remove the FreedomGPT directory again and try running yarn install and yarn start:prod again. Sometimes, errors can occur during installation or build processes, and retrying them can help.

Also, it looks like there are some warnings related to missing peer dependencies, which could be causing issues. You might want to try installing the missing packages or updating the existing ones.

If the issue persists, you can try looking at the specific error message and see if there are any relevant solutions or workarounds available online. Additionally, you can try reaching out to the Freedom GPT support team or community for help with troubleshooting the issue."

**Comment by bhattaraijay05** [comment]
It is because of the naming conflict in the root directory. Try the following steps and it will work.
```sh
  git clone https://github.com/ohmplatform/FreedomGPT.git freedom-gpt
  cd freedom-gpt
  yarn install
  yarn start:prod
```

**Comment by jdriscoll98** [comment]
@bhattaraijay05 i had the same issue as @ChubbyFungus and oddly enough your solution worked for me! I'm on MacOS 13.2.1 incase anyone runs into the same issue.

**Comment by Nguyenpham89** [comment]
Ok

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: jdriscoll98 ***@***.***>
Đã gửi: Thursday, April 13, 2023 12:34:37 PM
Đến: ohmplatform/FreedomGPT ***@***.***>
Cc: Subscribed ***@***.***>
Chủ đề: Re: [ohmplatform/FreedomGPT] Stuck downloading (Issue #28)


@bhattaraijay05<https://github.com/bhattaraijay05> i had the same issue as @ChubbyFungus<https://github.com/ChubbyFungus> and oddly enough your solution worked for me! I'm on MacOS 13.2.1 incase anyone runs into the same issue.

**Comment by AlwaysZmx** [comment]
You can download from this link https://huggingface.co/Sosaka/Alpaca-native-4bit-ggml/blob/main/ggml-alpaca-7b-q4.bin

**Comment by Sopwafel** [comment]
Thanks, AlwaysZmx! But where do I put it? I'm still not getting though this error.

**Comment by ChubbyFungus** [comment]
> 

Perfect thanks this got it working
